// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnwvhavrknuzoszbhoky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJud3ZoYXZya251em9zemJob2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzUzMDMsImV4cCI6MjA2OTY1MTMwM30.zemfaIfOvhISmb2mYmHr_MK1Qbn8GYyFpgd5yGxfElE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});